# Generated by Django 5.2.4 on 2025-07-26 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(max_length=200)),
                ('issued_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('delete_time', models.DateTimeField(null=True)),
                ('deleted_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='delete_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='deleted_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
