# Generated by Django 5.2.4 on 2025-07-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_certificate_delete_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='issued_date',
        ),
        migrations.AddField(
            model_name='contact',
            name='delete_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='deleted_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
