# Generated by Django 5.2.4 on 2025-07-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_certificate_image_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='deleted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
